---
  root: /user/work/ba18321/Abil/

  run_name: dec_2024_depth_env_vars_extra_pseudos #update for specific run name

  path_out:  studies/devries2024/ModelOutput/ #root + folder
  path_in:  predictions/ens/ #root + folder

  prediction:  studies/devries2024/data/env_data.csv #root + folder
  targets:  studies/devries2024/data/traits.csv #root + folder
  training:  studies/devries2024/data/obs_env.csv

  predictors: ["temperature", 
    "sio4", "po4", "no3", 
    "o2", "DIC", "TA",
    "PAR"]

  verbose: 3
  seed : 1 # random seed
  n_threads : 2 # how many cpu threads to use (local)
  cv : 10
  predict_probability: False 

  ensemble_config: 
    classifier: True
    regressor: True
    m1: "rf"
    m2: "xgb"
    m3: "knn"
     
  upsample: False
  stratify: True
  
  reg_scoring:
   R2: r2
   MAE: neg_mean_absolute_error
   RMSE: neg_root_mean_squared_error

  clf_scoring:
   accuracy: balanced_accuracy

  param_grid:
    rf_param_grid:
      reg_param_grid:
        n_estimators: [250]
        max_features:  ['sqrt', 0.1, 0.2, 0.4, 0.6, 0.8, 1]
        max_depth: [2, 10, 51, 75, 100, inf]
        min_samples_leaf: [1, 5, 13, 25, 37, 50]
        max_samples: [0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 1]     
      clf_param_grid:  
        n_estimators: [250]
        max_features:  ['sqrt', 1, 2, 4, 6, 8, 10]
        max_depth: [2, 10, 51, 75, 100, inf]
        min_samples_leaf: [1, 5, 13, 25, 37, 50]
        max_samples: [0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 1]     


    xgb_param_grid:
      reg_param_grid:  
        learning_rate: [0.01, 0.015, 0.025, 0.05, 0.1]
        n_estimators: [100]
        max_depth: [2, 5, 7, 10, 51, 100, inf]
        subsample: [0.4, 0.6, 0.7, 0.8, 1]
        colsample_bytree: [0.5, 0.667, 0.8, 0.9, 0.95, 0.975, 1]
        gamma: [0] 
        reg_alpha: [0, 0.1]
      clf_param_grid:  
        learning_rate: [0.01, 0.015, 0.025, 0.05, 0.1]
        n_estimators: [100]
        max_depth: [2, 5, 7, 10, 51, 100, inf]
        subsample: [0.4, 0.6, 0.7, 0.8, 1]
        colsample_bytree: [0.5, 0.667, 0.8, 0.9, 0.95, 0.975, 1]
        gamma: [0] 
        reg_alpha: [0, 0.1]
    knn_param_grid:
      reg_param_grid:  
        max_samples: [0.6, 0.8, 0.85, 0.9, 1]
        max_features: [0.6, 0.8, 0.85, 0.9, 1]
        estimator__leaf_size: [10, 30, 50]
        estimator__n_neighbors: [3, 5, 8, 10]
        estimator__p:  [1,2]        
        estimator__weights: ["uniform", "distance"]
      clf_param_grid:  
        max_samples: [0.6, 0.8, 0.85, 0.9, 1]
        max_features: [0.6, 0.8, 0.85, 0.9, 1]
        estimator__leaf_size: [10, 30, 50]
        estimator__n_neighbors: [3, 5, 8, 10]
        estimator__p:  [1,2]        
        estimator__weights: ["uniform", "distance"]
  knn_bagging_estimators: 30

